# Generated by Django 4.2.10 on 2024-02-17 19:20

import aktos.common.encrypted_fields
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConsumerAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "address1",
                    aktos.common.encrypted_fields.EncryptedCharField(max_length=2048),
                ),
                (
                    "address2",
                    aktos.common.encrypted_fields.EncryptedCharField(
                        blank=True, max_length=2048, null=True
                    ),
                ),
                (
                    "city",
                    aktos.common.encrypted_fields.EncryptedCharField(max_length=2048),
                ),
                (
                    "state",
                    aktos.common.encrypted_fields.EncryptedCharField(
                        choices=[
                            ("AL", "Alabama"),
                            ("AK", "Alaska"),
                            ("AZ", "Arizona"),
                            ("AR", "Arkansas"),
                            ("CA", "California"),
                            ("CO", "Colorado"),
                            ("CT", "Connecticut"),
                            ("DE", "Delaware"),
                            ("DC", "District of Columbia"),
                            ("FL", "Florida"),
                            ("GA", "Georgia"),
                            ("HI", "Hawaii"),
                            ("ID", "Idaho"),
                            ("IL", "Illinois"),
                            ("IN", "Indiana"),
                            ("IA", "Iowa"),
                            ("KS", "Kansas"),
                            ("KY", "Kentucky"),
                            ("LA", "Louisiana"),
                            ("ME", "Maine"),
                            ("MD", "Maryland"),
                            ("MA", "Massachusetts"),
                            ("MI", "Michigan"),
                            ("MN", "Minnesota"),
                            ("MS", "Mississippi"),
                            ("MO", "Missouri"),
                            ("MT", "Montana"),
                            ("NE", "Nebraska"),
                            ("NV", "Nevada"),
                            ("NH", "New Hampshire"),
                            ("NJ", "New Jersey"),
                            ("NM", "New Mexico"),
                            ("NY", "New York"),
                            ("NC", "North Carolina"),
                            ("ND", "North Dakota"),
                            ("OH", "Ohio"),
                            ("OK", "Oklahoma"),
                            ("OR", "Oregon"),
                            ("PA", "Pennsylvania"),
                            ("RI", "Rhode Island"),
                            ("SC", "South Carolina"),
                            ("SD", "South Dakota"),
                            ("TN", "Tennessee"),
                            ("TX", "Texas"),
                            ("UT", "Utah"),
                            ("VT", "Vermont"),
                            ("VA", "Virginia"),
                            ("WA", "Washington"),
                            ("WV", "West Virginia"),
                            ("WI", "Wisconsin"),
                            ("WY", "Wyoming"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "zip_code",
                    aktos.common.encrypted_fields.EncryptedCharField(max_length=32),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Consumer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("ref_id", models.UUIDField(default=uuid.uuid4)),
                (
                    "ssn",
                    aktos.common.encrypted_fields.EncryptedCharField(max_length=2048),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[
                            ("INACTIVE", "Inactive"),
                            ("PAID_IN_FULL", "Paid In Full"),
                            ("IN_COLLECTION", "In Collection"),
                        ],
                        default="INACTIVE",
                        max_length=100,
                        no_check_for_status=True,
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=10,
                        default=Decimal("0.0"),
                        help_text="The balance amount",
                        max_digits=18,
                    ),
                ),
                (
                    "address",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumer",
                        to="consumers.consumeraddress",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "ref_id")},
            },
        ),
    ]
